### ISSUE TITLE
`npm test` fails because missing dependency `morgan`

### ISSUE THREAD

**Issue by keheliya** [capaj/Moonridge#8]
After running `npm test` I get the following error.

```
npm test

> moonridge@0.8.8 test /Users/keheliya/dev/Moonridge
> mocha

  basic CRUD including working liveQueries
module.js:338
    throw err;
    ^
Error: Cannot find module 'morgan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/keheliya/dev/Moonridge/test/e2e-smoketest/server.js:16:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I think `morgan` is used by server.js

**Comment by capaj** [comment]
you're right, as it is now, those dependencies don't get installed by default.
